export const FIELD_ACTIVITY = [
   'Serveuse/eur',
   'Gerante',
   'Assistant(e)',
   'Commercial(e)',
   'hôtellerie',
   'coursier',
   'chauffeur',
   'cuisinier',
   'Chaudronnier',
   'Chef "d\'equipe", "Acousticien,"Fraiseur/euse industriel","Métallier-charpentier',
   'Soudeur(euse) industriel',
   'Technicien(ne) en chaudronnerie industrielle","Tourneur/euse industriel',
   'Tuyauteur industriel',
   'Administrateur',
   'Administration Des Entreprises',
   'Administration Générale',
   'Agent De Programme',
   'Agent Des Services Techniques',
   'Analyste Programmeur',
   'Archiviste',
   'Assistant',
   'Avocat',
   'Bibliothécaire',
   'Business Of Administration',
   'Chef Cantonnier',
   'Chef De Quart',
   'Commissaire',
   'Compteur',
   'Contentieux',
   'Contrôleur',
   'Coopération',
   'Criminologie',
   'Dactylographie',
   'Déclarant En Douanes',
   'Défense Des Cultures',
   'Développement',
   'Diplomatie',
   'Documentaliste',
   'Douanes',
   'Droit Du Travail',
   ' Affaires Sociales',
   'Contrôle Du Travail',
   'Droit Entreprise',
   'Employé De Bureau',
   'Agent Releveur',
   'Ethnologie Sociologie',
   'Droit Public',
   'Formations Juridiques',
   'Généraliste',
   'Huissier De Justice',
   'Magistrat',
   'Notariat',
   'Prospecteur',
   'Relations Internationales',
   'Secrétaire Bilingue-Trilingue',
   'Secrétaire Comptable',
   'Secrétaire De Direction',
   'Secrétaire Médical',
   'Secrétariat',
   'Secrétariat Juridique',
   'Sténodactylographie',
   'Téléphoniste',
   'Standardiste',
   'Télexiste',
   'Agriculture (Sans Précision)',
   'Agriculture Tropicale',
   'Agronomie',
   'Agro-pédologie',
   'Chasse',
   'Ecole Forestière',
   'Elevage De Bovins',
   'Dressage Des Bœufs',
   'Élevage De Caprins',
   'Elevage De Lapins',
   'Elevage De Porcins',
   'Elevage De Volailles',
   'Elevage D’ovins',
   'Elevage Tropicale',
   'Encadreur De Pêche',
   'Génie Rural',
   'Lieutenant De Pêche',
   'Pêche',
   'Pêche Continentale',
   'Phytotechnie',
   'Pisciculture',
   'Pisciculture Et Pêche',
   'Production Végétale Et Animale',
   'Sylviculture',
   'Techniques Agricoles',
   'Zootechnie',
   'Agent Immobilier',
   'Architecture',
   'Architecture Intérieure',
   'Bâtiment',
   'Bâtiment Et Urbanisme',
   'Bâtiment Travaux Publics',
   'Béton Armé',
   'Cadastre',
   'Capacité au Bornage',
   'Carrelage',
   'Charpente',
   'Charpente Métallique',
   ' Montage',
   'Chef De Chantier',
   'Chef d’Equipe Engins',
   'Chef Secteur Routier',
   'Coffreur',
   'Conducteur De Travaux Publics',
   'Construction Routes',
   'Dessinateur En Bâtiment',
   'Dessinateur En Genie Civil',
   'Dessinateur En Genie Rural',
   'Genie Civil',
   'Géographe (Photogrammétrie,Cartographie)',
   'Géomètre',
   'Hydraulique',
   'Infrastructure',
   'Maçonnerie',
   'Métreur',
   'Peinture',
   'Peinture En Bâtiment',
   'Plomberie- Sanitaire- Zinguerie',
   'Ponts Et Chaussées',
   'Projeteur En Bâtiment',
   'Serrurerie, Topographie',
   'Travaux Publics',
   'Urbaniste Voies Et Bâtiments',
   'Caissier',
   'Commerce',
   'Contrôleur De Prix',
   'Courtage Distribution',
   'Electro-Commerciaux',
   'Employé Des Services Commerciaux (BEP, BT Commerciaux, Etc.)',
   'Gestion Commerciale',
   'Hautes Etudes Commerciales',
   'Inspecteur Commercial Et Administratif',
   'Inspectorat ',
   'Marketing Management',
   'Réception Gestion',
   'Receveur Représentation',
   'Démarchage',
   'Techniques Commerciales',
   'Vendeur',
   'Gérant ',
   'Animateur Audiovisuel',
   'Communication',
   'Gestionnaire De Stock',
   'Impression',
   'Edition',
   'Journalisme',
   'Offsettiste',
   ' Poste Et Télécom',
   'Publicité',
   'Radiotélégraphiste',
   'Sérigraphe',
   'Exploitation Des Circuits Fermés De Télévision',
   'Technique Des Télécommunication ',
   'Télécommunications Et Signalisations',
   'Téléphone (Réparation)',
   'Télex (Réparation)',
   'Transmission Radio',
   'Aide Jardinière',
   'Aide Maternelle',
   'Alphabétisation',
   'Animation Rurale',
   'Conseiller d’EPS',
   'Conseiller Rural',
   'Educateur d’Internat',
   'Education Permanente',
   'Education Physique Et Sportive',
   'Educatrice Préscolaire',
   'Enseignement',
   'Français',
   'Histoire',
   'Géographie',
   'Lettres',
   'Inspecteur',
   'Instituteur',
   'Instituteur Adjoint',
   'Instructeur Jardinière',
   'Langues',
   'Physique Chimie',
   'Maths',
   'Professeur De Mathématiques',
   'Professeur d’Eps',
   'Psychologie Appliquée',
   'Psychologie',
   'Philosophie',
   'Sciences De l’Education',
   'Sciences Naturelles',
   'Théologie',
   'Agroéconomie',
   'Assurances',
   'Banques',
   'Comptabilité',
   'Crédit Et Autres',
   'Econome',
   'Economie',
   'Economie Et Finances',
   'Finances Comptabilité',
   'Gestion',
   'Impôts',
   'Océanographie',
   'Planification',
   'Prévisionniste',
   'Sciences Et Techniques Comptables Et Financières',
   'Statisticien Economiste',
   'Statistique',
   'travaux Statistiques',
   'Trésor',
   'Boulangerie Pâtisserie',
   'Cuisine',
   'Hôtesse',
   'Restauration Bar',
   'Agro-Alimentaire',
   'Génie-Alimentaire',
   'Tricotage',
   'Boucherie-Charcuterie',
   'Boucherie',
   'Charcuterie',
   'Transformation Des Produits Agricoles (Brasserie, Conserverie, Oenologie, Etc)',
   'Biochimie',
   'Chimie',
   'Chimie-Industrielle',
   'Thermicien',
   'Bobinage',
   'Dépanneur Radio TV',
   'Electricien De Contrôle',
   'Electricien De Distribution',
   'Electricien De Réseau',
   'Electricité Auto',
   'Electricité Equipement',
   'Electricité Générale',
   'Electricité Industrielle',
   'Electricité-Bâtiment',
   'Electromécanique',
   'Electronique',
   'Electrotechnique',
   'Equipement ',
   'Horlogerie',
   'Horloger Rhabilleur',
   'Radioélectricité',
   'Bijouterie',
   'Bonneterie',
   'Broderie',
   'Confection',
   'Cordonnerie',
   'Coupe-Couture',
   'Broderie ',
   'Fabrication De Chaussures (Cuirs Ou Plastiques)',
   'Filature',
   'Géodésie',
   'Géologie',
   'Maroquinerie',
   'Mécanique Entretien Machine',
   'Mines',
   'Géologie',
   'Carrières',
   'Miroiterie',
   'Vitrerie',
   'Optique',
   'Prospection',
   'Forage',
   'Raffinage',
   'Sellerie',
   'Bourrellerie',
   'Textile',
   'Tissage',
   'Verrerie',
   'Affûtage',
   'Agro-mécanique',
   'Ajustage',
   'Carrosserie',
   'Chaudronnerie',
   'Construction Métallique',
   'Construction Métallique',
   'Ferronnerie (Métaux)',
   'Construction Navale',
   'Couvreur Zingueur',
   'Dessin Industriel',
   'Diéséliste',
   'Diéseliste Mécanique De Moteurs',
   'Mécanique Poids Lourds',
   'Fonderie',
   'Fraisage',
   'Génie Mécanique',
   'Laminage',
   'Matériel Et Traction',
   'Mécanicien (Sans Précision)',
   'Mécanicien Navigant',
   'Mécanique Auto',
   'Mécanique Engins',
   'Mécanique Entretien',
   'Mécanique Générale',
   'Mécanique Générale',
   'Fabrication Mécanique',
   'Métaux Mécanique Electricité',
   'Météorologie',
   'Moulage',
   'Officier Mécanicien',
   'Outillage Contrôle Métrologie',
   'Petite Mécanique',
   'Rectifiage',
   'Relieur',
   'Brochage',
   'Massicot',
   'Sciage',
   'Affûtage',
   'Tôlerie',
   'Soudure Tournage',
   'Tournage',
   'Fraisage',
   'Ajustage',
   'Ameublement',
   'Ebénisterie',
   'Menuiserie',
   'Menuiserie Charpente',
   'Menuiserie Ebenisterie',
   'Concepteur Multimédia',
   'Informatique',
   'Ingénieur De Conception',
   'Maintenance Informatique',
   'Mécanographie',
   'Opérateur Pupitreur',
   'Perforation',
   'Programmation',
   'Arts Graphiques',
   'Arts Menagers',
   'Arts Plastiques',
   'Arts',
   'Beaux Arts',
   'Céramique',
   'Cinéaste',
   'Cinéma (Labo, Réparation, Prise De Vue)',
   'Décoration',
   'Graphiste Et Décorateur',
   'Gravure',
   'Guide',
   'Linotypiste',
   'Musée',
   'Musique',
   'Photographe',
   'Photograveur',
   'Réalisateur De Films Et De Télévision',
   'Sculpture-Parure',
   'Styliste Modéliste',
   'Tannerie',
   'Tapisserie Et Agencement',
   'Teinture (Impression)',
   'Théâtre Animation Culturelle Comédie',
   'Tourisme',
   'Vannerie',
   'Vernisseur',
   'Ponceur',
   'Colleur',
   'Plaqueur',
   'Aide Assistant(e) Social(e)',
   'Agent d’Hygiène',
   'Analyses Médicales',
   'Biologiste',
   'Chirurgie',
   'Dentiste',
   'Diététique',
   'Gynécologie',
   'Infirmier',
   'Infirmière',
   'Infirmier',
   'Infirmière Et Sage-Femme',
   'Laborantin',
   'Radio',
   'Agent d’accueil',
   'Chauffeur',
   'Transport logistique',
   'Transit',
   'Declarant En Douane',
   'Sans Spécialité',
   'Ressources Humaines',
   'Audit Et Contrôle De Gestion',
   'Télécommunications',
   'Juridique',
   'Construction Métallique',
   'Etablissement Financier',
   'Ressources Humaines Et Communication',
   'Etablissement Financier',
   'Promotrice',
   'Management De La Qualité',
   'Sécurité Défense',
   'Commercial En Banque',
   'Sécurité',
   'Gestion',
   'Sécurité',
   'Construction Métallique',
   'Secteur Privé',
   'Juriste',
   'Autolerie',
   'Droit Et Commerce',
   'Juriste',
   'Hygiéniste Industriel',
   'Hygiéniste Industriel',
   'Markéting Et Négociation',
   'Assistant Administratif',
   'Gestionnaire De Stock',
   'Management De La Qualité',
   'Audit',
   'Tout Type De Métier',
   'Tout Emploi',
   'Ressources Humaines Et Communication',
   'Psychologie Sociale Et Du Travail',
   'Coursier',
   'Sociologue Agent De Projet d’Assainissement',
   'Informel',
   'Commerce',
   'Eau Et Environnement',
   'Hygiène Sécurité Environnement',
   'Caissière',
   'Psychologie Clinique',
   'Psychothérapie',
   'Prevention Des Risques Et Sécurité Incendie',
   'Chauffeur',
   'Psychologie',
   'Construction Métallique',
   'Imprimerie',
   'Psychologie',
   'Finance Comptabilité Et Gestion Des Entreprises',
   'Service Humanitaire',
   'Gestion De Projets',
   'Marketing',
   'Animatrice',
   'Ouvrier',
   'Mines Géologie Pétrole',
   'Science de l’Information',
   'Distribution De Produits',
   'Accueil Hôtelier',
   'Caissière',
   'Droit Des Affaires Option Fiscalite',
   'Droit',
   'Menuiserie Aluminium',
   'Eau Et Environnement',
   'Expert En Eau',
   'Environnement',
   'Administration Et Communication',
   'Tourisme Et Loisirs',
   'Communication Et Administration',
   'Conseiller Psychologue',
   'Sociologie',
   'Logistique',
   'Environnement Et Ressources Naturelles',
   'Cariste',
   'Electricien',
   'Eau',
   'Forage',
   'Marchés Publics',
   'Eau',
   'Forage',
   'Assainissement Et Marchés Publics',
   'Mécanicien',
   'Operateur',
   'Assistante En Ressources Humaines, Transit',
   'Transport Logistique',
   'Femme De Chambre',
   'Pétrole Et Gaz',
   'Anglais',
   'Construction Métallique',
   'Couture',
   'Gestion Des Collectivités',
   'Secrétariat Et Environnement',
   'Secteur Juridique',
   'Répétiteur',
   'Conducteur',
   'Agence De Voyage',
   'Acheteur',
   'Secrétariat',
   'Agent Entretien',
   'Rayonniste',
   'Réceptionniste',
   'Energie Renouvelable',
   'Délégué Médical',
   'Sciences Politique',
   'Criminologie',
   'Réseaux Informatiques',
   'Couture',
   'Hygiène Et Sécurité',
   'Agent De Sécurité',
   'Droit Prive',
   'Ntic',
   'Sociologie',
   'Auxiliaire En Pharmacie',
   'Médecin',
   'Journalisme',
   'Gestion De l’Environnement Et Des Ressources Naturelles',
   'Assistante Sociale',
   'Anthropologie',
   'Secourisme',
   'Assistanat De Direction',
   'Evaluation De Projet',
   'Aide Social',
   'Sanitaire Social',
   'Aucune',
];
