export const skills = [
   'HTML5',
   'CSS3',
   'JavaScript',
   'TypeScript',
   'Vue.js',
   'React',
   'Angular',
   'Node.js',
   'Express.js',
   'MongoDB',
   'MySQL',
   'PHP',
   'Laravel',
   'Symfony',
   'Java',
   'Kotlin',
   'Swift',
   'Objective-C',
   'React Native',
   'Flutter',
   'Python',
   'R',
   'SQL',
   'NumPy',
   'Pandas',
   'Scikit-learn',
   'TensorFlow',
   'Keras',
   'PyTorch',
   'Adobe Photoshop',
   'Adobe Illustrator',
   'Adobe XD',
   'Figma',
   'Sketch',
   'SEO',
   'SEA',
   'Google Analytics',
   'Google AdWords',
   'Réseaux sociaux (Facebook, Instagram, Twitter, LinkedIn)',
   'Email marketing',
   'Agile (Scrum, Kanban)',
   'Waterfall',
   'JIRA',
   'Trello',
   'Asana',
   'Monday.com',
   'Leadership',
   'Communication',
   'Gestion du temps',
   'Résolution de problèmes',
   'Prise de décisions',
   'Gestion des conflits',
   'Comptabilité',
   'Analyse financière',
   'Planification budgétaire',
   'Gestion de trésorerie',
   'Investissements',
   'Fiscalité',
   'Recrutement',
   'Formation',
   'Gestion des performances',
   'Rémunération et avantages sociaux',
   'Relations avec les employés',
   'Conformité légale',
   "Développement web",
   "Développement mobile",
   "Développement logiciel",
   "Intelligence artificielle",
   "Apprentissage automatique",
   "Réseaux informatiques",
   "Sécurité informatique",
   "Gestion de projet informatique",
   "Base de données",
   "Cloud computing",
   "Architecture logicielle",
   "Analyse de données",
   "Conception de systèmes",
   "Administration de systèmes",
   "Marketing digital",
      "Gestion de projet marketing",
      "Analyse de marché",
      "Communication",
      "Planification stratégique",
      "Publicité en ligne",
      "SEO",
      "SEM",
      "Analyse de données marketing",
      "Gestion de la marque",
      "Gestion des médias sociaux",
      "Relations publiques",
      "Comptabilité",
      "Analyse financière",
      "Gestion de trésorerie",
      "Investissements",
      "Banque d'investissement",
      "Banque commerciale",
      "Planification financière",
      "Contrôle de gestion",
      "Gestion des risques",
      "Fiscalité",
      "Gestion de portefeuille",
      "Services bancaires en ligne",
      "Recrutement",
      "Formation",
      "Gestion des carrières",
      "Relations sociales",
      "Gestion de la paie",
      "Planification des effectifs",
      "Développement organisationnel",
      "Gestion des performances",
      "Relations employeur-employé",
      "Rémunération et avantages sociaux",
      "Conseil en ressources humaines",
      "Gestion de la diversité et de l'inclusion",
      "Ingénierie mécanique",
      "Ingénierie électrique",
      "Ingénierie civile",
      "Ingénierie industrielle",
      "Ingénierie de la production",
      "Ingénierie logistique",
      "Ingénierie environnementale",
      "Ingénierie chimique",
      "Ingénierie pétrolière",
      "Ingénierie minière",
      "Ingénierie nucléaire",
      "Ingénierie des matériaux",
      "Médecine",
      "Soins infirmiers",
      "Kinésithérapie",
      "Médecine dentaire",
      "Médecine vétérinaire",
      "Pharmacie",
      "Recherche médicale",
      "Administration de la santé",
      "Gestion hospitalière",
      "Épidémiologie",
      "Santé publique",
      "Santé mentale"
];
